using System.Collections.Generic; namespace StayAwake { static class Strings { public static readonly Dictionary<string,string[]> Text=new Dictionary<string,string[]> {
 {"normalMode",new[]{"正常模式","正常模式","Normal Mode"}},
 {"awakeMode",new[]{"合盖运行模式","闔蓋運行模式","Closed-Lid Mode"}},
 {"awakeNotApplied",new[]{"合盖运行未生效","闔蓋運行未生效","Closed-Lid Mode Not Applied"}},
 {"normalNotRestored",new[]{"未能恢复正常模式","未能恢復正常模式","Could Not Restore Normal Mode"}},
 {"statusUnknown",new[]{"无法确认系统状态","無法確認系統狀態","System Status Unknown"}},
 {"normalDetail",new[]{"Windows 会遵循系统休眠设置","Windows 會遵循系統睡眠設定","Windows follows system sleep settings"}},
 {"awakeDetail",new[]{"系统实际状态已确认","系統實際狀態已確認","System status confirmed"}},
 {"stillPreventingSleep",new[]{"系统仍在阻止休眠","系統仍在阻止睡眠","The system is still preventing sleep"}},
 {"sleepAllowed",new[]{"系统当前允许休眠","系統目前允許睡眠","The system currently allows sleep"}},
 {"unknownDetail",new[]{"请重新检测后再决定是否合盖","請重新檢查後再決定是否闔蓋","Check again before closing the lid"}},
 {"enableAwake",new[]{"开启合盖运行","開啟闔蓋運行","Enable Closed-Lid Mode"}},
 {"restoreNormal",new[]{"恢复正常模式","恢復正常模式","Restore Normal Mode"}},
 {"retryAwake",new[]{"重新开启合盖运行","重新開啟闔蓋運行","Retry Closed-Lid Mode"}},
 {"retryNormal",new[]{"重新恢复正常模式","重新恢復正常模式","Retry Restoring Normal Mode"}},
 {"refresh",new[]{"重新检测","重新檢查","Check Again"}},
 {"checking",new[]{"正在检测…","正在檢查…","Checking…"}},
 {"enabled",new[]{"已开启","已開啟","On"}},
 {"disabled",new[]{"未开启","未開啟","Off"}},
 {"unconfirmed",new[]{"无法确认","無法確認","Unknown"}},
 {"notChecked",new[]{"尚未检测","尚未檢查","Not Yet Checked"}},
 {"keepAwake",new[]{"保持合盖运行","保持闔蓋運行","Keep Closed-Lid Mode"}},
 {"useNormal",new[]{"使用正常模式","使用正常模式","Use Normal Mode"}},
 {"readStatusFailed",new[]{"无法读取系统休眠状态，请重新检测。","無法讀取系統睡眠狀態，請重新檢查。","Could not read the system sleep status. Please check again."}},
 {"enableFailed",new[]{"无法开启合盖运行，请重试。","無法開啟闔蓋運行，請重試。","Could not enable closed-lid mode. Please try again."}},
 {"restoreFailed",new[]{"无法恢复正常模式，请重试。","無法恢復正常模式，請重試。","Could not restore normal mode. Please try again."}},
 {"confirmStatusFailed",new[]{"无法确认系统状态，请重新检测。","無法確認系統狀態，請重新檢查。","Could not confirm the system status. Please check again."}},
 {"allowSleepHint",new[]{"允许 Windows 按系统设置休眠","允許 Windows 按系統設定睡眠","Allow Windows to sleep according to system settings"}},
 {"enableAwakeHint",new[]{"开启合盖运行模式","開啟闔蓋運行模式","Enable closed-lid mode"}},
 {"autoCheck",new[]{"每 5 秒自动检测 · 仅窗口打开时","每 5 秒自動檢查 · 僅視窗開啟時","Checks every 5 seconds · While this window is open"}},
 {"standardAppearance",new[]{"默认","預設","Default"}},
 {"frostedGlass",new[]{"极光磨砂","極光磨砂","Aurora Glass"}},
 {"midnight",new[]{"午夜蓝","午夜藍","Midnight Blue"}},
 {"warmSand",new[]{"暖砂","暖砂","Warm Sand"}},
 {"appearance",new[]{"外观","外觀","Appearance"}},
 {"switchLanguage",new[]{"切换语言/Switch Language","切換語言/Switch Language","Switch Language"}},
 {"quit",new[]{"退出","結束","Quit"}},
 {"appMenu",new[]{"应用菜单","應用程式選單","App Menu"}},
 {"currentStatus",new[]{"当前状态","目前狀態","Current Status"}},
 {"preventSystemSleep",new[]{"防止系统休眠","防止系統睡眠","Prevent System Sleep"}},
 {"lastChecked",new[]{"最后检测","上次檢查","Last Checked"}},
 {"actualSystemStatus",new[]{"系统实际状态","系統實際狀態","Actual System Status"}}
}; } }